
/*
source file can be found at:
https://github.com/payara/Payara/blob/master/nucleus/security/core/src/main/resources/config/login.conf
*/

jdbcRealm {
  com.sun.enterprise.security.ee.authentication.glassfish.jdbc.JDBCLoginModule required;
};
